services:
  - name: spam-classifier
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 app:app"
    envVars:
      - key: PORT
        value: 10000
